apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  KC_HOSTNAME_URL: "http://localhost:9090"
  KC_HOSTNAME_STRICT: "false"
  KEYCLOAK_ADMIN: "admin"
  KC_DB: "postgres"
  KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak"
  KC_DB_USERNAME: "postgres"
