version: "3.9"

services:

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: finance_keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"

  postgres:
    image: postgres:16
    container_name: finance_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 253421
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
