
services:

  redis:
    image: redis:alpine
    container_name: finance-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-gui
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8085:8081"
    depends_on:
      - redis
    networks:
      - finance-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: finance_keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import

  postgres:
    image: postgres:16
    container_name: finance_db
    restart: always
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 253421
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finance-network

networks:
  finance-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
