version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: finance_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 253421
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
