filebeat.inputs:
  - type: filestream
    id: local-spring-logs
    enabled: false
    paths:
      - /logs/*.log
    parsers:
      - ndjson:
          target: ""
          overwrite_keys: true
          add_error_key: true

  - type: filestream
    id: docker-container-logs
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*.log
    parsers:
      - container: ~
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - drop_event:
          when:
            equals:
              container.name: "finance_filebeat"


output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "finance-logs-%{+yyyy.MM.dd}"

setup.ilm.enabled: false
setup.template.name: "finance-logs"
setup.template.pattern: "finance-logs-*"

logging.level: info