
CREATE TABLE instruments (
                             id uuid NOT NULL,
                             symbol varchar(255) UNIQUE,
                             name varchar(255),
                             type varchar(255) CHECK (type IN ('FIAT','STOCK','CRYPTO','COMMODITY','FOREX','INDEX','BOND')),
                             current_price numeric(38,2),
                             is_active boolean NOT NULL,
                             last_update_time timestamp(6),
                             PRIMARY KEY (id)
);

CREATE TABLE market_data (
                             id uuid NOT NULL,
                             instrument_id uuid,
                             price numeric(38,2),
                             timestamp timestamp(6),
                             PRIMARY KEY (id)
);

CREATE TABLE portfolios (
                            id uuid NOT NULL,
                            user_id varchar(255),
                            name varchar(255),
                            cash_balance numeric(38,2),
                            PRIMARY KEY (id)
);

CREATE TABLE portfolio_items (
                                 id uuid NOT NULL,
                                 portfolio_id uuid,
                                 instrument_id uuid,
                                 quantity numeric(38,2),
                                 average_cost numeric(38,2),
                                 PRIMARY KEY (id)
);

CREATE TABLE transactions (
                              id bigint GENERATED BY DEFAULT AS IDENTITY,
                              user_id varchar(255),
                              instrument_id uuid,
                              type smallint CHECK (type BETWEEN 0 AND 1),
                              quantity numeric(38,2),
                              price numeric(38,2),
                              total_amount numeric(38,2),
                              commission numeric(38,2),
                              timestamp timestamp(6) NOT NULL,
                              PRIMARY KEY (id)
);

CREATE TABLE user_favorite_instruments (
                                           id bigint GENERATED BY DEFAULT AS IDENTITY,
                                           user_id varchar(255) NOT NULL,
                                           instrument_id uuid NOT NULL,
                                           added_at timestamp(6) NOT NULL,
                                           PRIMARY KEY (id)
);


ALTER TABLE IF EXISTS market_data
    ADD CONSTRAINT fk_market_data_instrument
    FOREIGN KEY (instrument_id)
    REFERENCES instruments;

ALTER TABLE IF EXISTS portfolio_items
    ADD CONSTRAINT fk_portfolio_items_instrument
    FOREIGN KEY (instrument_id)
    REFERENCES instruments;

ALTER TABLE IF EXISTS portfolio_items
    ADD CONSTRAINT fk_portfolio_items_portfolio
    FOREIGN KEY (portfolio_id)
    REFERENCES portfolios;

ALTER TABLE IF EXISTS transactions
    ADD CONSTRAINT fk_transactions_instrument
    FOREIGN KEY (instrument_id)
    REFERENCES instruments;

ALTER TABLE IF EXISTS user_favorite_instruments
    ADD CONSTRAINT fk_user_favorites_instrument
    FOREIGN KEY (instrument_id)
    REFERENCES instruments;