spring.application.name=news-service
logging.level.org.springframework.security=DEBUG
server.port=8082
#postgre
spring.datasource.url=jdbc:postgresql://localhost:5432/news_db
spring.datasource.username=postgres
spring.datasource.password=253421

spring.threads.virtual.enabled=true

#otel
management.tracing.sampling.probability=0.1
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces

#keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/FinancePortal
keycloak.clientId=finance-gateway-client

#orm
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}
#news-api
news.api.key=${NEWS_API_KEY}
news.api.url=${NEWS_API_URL}