spring.application.name=api-gateway

server.port=8080

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/FinancePortal
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9090/realms/FinancePortal/openid-connect/certs


spring.cloud.gateway.default-filters[0]=TokenRelay

spring.cloud.gateway.routes[0].id=news-service
spring.cloud.gateway.routes[0].uri=http://localhost:8082
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/news/**

spring.cloud.gateway.routes[1].id=finance-service
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/market/**, /api/trade/**, /api/portfolio/**


