spring.application.name=api-gateway
server.port=8080

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/FinancePortal

# News Service Routes
spring.cloud.gateway.server.webflux.routes[0].id=news-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/news/**



# Finance Service Routes
spring.cloud.gateway.server.webflux.routes[1].id=finance-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/market/**,/api/trade/**,/api/portfolio/**,/api/admin/**,/api/inflation/**

# Swagger/OpenAPI document routes
spring.cloud.gateway.server.webflux.routes[2].id=finance-openapi
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/finance/v3/api-docs
spring.cloud.gateway.server.webflux.routes[2].filters[0]=RewritePath=/finance/v3/api-docs,/v3/api-docs

spring.cloud.gateway.server.webflux.routes[3].id=news-openapi
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/news/v3/api-docs
spring.cloud.gateway.server.webflux.routes[3].filters[0]=RewritePath=/news/v3/api-docs,/v3/api-docs

spring.cloud.gateway.server.webflux.routes[4].id=classification-openapi
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/classification/v3/api-docs
spring.cloud.gateway.server.webflux.routes[4].filters[0]=RewritePath=/classification/v3/api-docs,/v3/api-docs

spring.cloud.gateway.server.webflux.routes[5].id=classification-api
spring.cloud.gateway.server.webflux.routes[5].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/v1/news/**

springdoc.swagger-ui.urls[0].name=Finance Service
springdoc.swagger-ui.urls[0].url=/finance/v3/api-docs
springdoc.swagger-ui.urls[1].name=News Service
springdoc.swagger-ui.urls[1].url=/news/v3/api-docs
springdoc.swagger-ui.urls[2].name=Classification API
springdoc.swagger-ui.urls[2].url=/classification/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.oauth2=TRACE
logging.level.org.springframework.web.reactive.function.client=TRACE
