apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: finance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: api-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-gateway-config
          resources:
            requests:
              cpu: 200m
              memory: 1000Mi
            limits:
              cpu: 500m
              memory: 1000Mi
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            failureThreshold: 3
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8080
            periodSeconds: 5
            failureThreshold: 2
          readinessProbe:
            tcpSocket:
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
