apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: finance
data:
  KEYCLOAK_ISSUER_URI: "http://localhost:9090/realms/FinancePortal"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "http://keycloak:8080/realms/FinancePortal/protocol/openid-connect/certs"
  MANAGEMENT_OTLP_METRICS_EXPORT_URL: "http://grafana-lgtm-service:4318/v1/metrics"
  MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT: "http://grafana-lgtm-service:4318/v1/traces"
  MANAGEMENT_OTLP_LOGS_EXPORT_URL: "http://grafana-lgtm-service:4318/v1/logs"
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_ID: "news-service"
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_URI: "http://news-service:8082"
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_PREDICATES_0: "Path=/api/news/**"
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_1_ID: "finance-service"
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_1_URI: "http://finance-service:8081"
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_1_PREDICATES_0: "Path=/api/market/**,/api/trade/**,/api/portfolio/**,/api/admin/**,/api/inflation/**"
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_2_ID: "finance-openapi"
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_2_URI: "http://finance-service:8081"
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_2_PREDICATES_0: "Path=/finance/v3/api-docs"
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_2_FILTERS_0: "RewritePath=/finance/v3/api-docs,/v3/api-docs"
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_3_ID: "news-openapi"
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_3_URI: "http://news-service:8082"
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_3_PREDICATES_0: "Path=/news/v3/api-docs"
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_3_FILTERS_0: "RewritePath=/news/v3/api-docs,/v3/api-docs"
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_4_ID: "classification-openapi"
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_4_URI: "http://classification-api:8083"
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_4_PREDICATES_0: "Path=/classification/v3/api-docs"
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_4_FILTERS_0: "RewritePath=/classification/v3/api-docs,/v3/api-docs"
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_5_ID: "classification-api"
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_5_URI: "http://classification-api:8083"
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_5_PREDICATES_0: "Path=/api/v1/news/**"
  SPRINGDOC_SWAGGER_UI_URLS_0_NAME: "Finance Service"
  SPRINGDOC_SWAGGER_UI_URLS_0_URL: "/finance/v3/api-docs"
  SPRINGDOC_SWAGGER_UI_URLS_1_NAME: "News Service"
  SPRINGDOC_SWAGGER_UI_URLS_1_URL: "/news/v3/api-docs"
  SPRINGDOC_SWAGGER_UI_URLS_2_NAME: "Classification API"
  SPRINGDOC_SWAGGER_UI_URLS_2_URL: "/classification/v3/api-docs"
  SPRINGDOC_SWAGGER_UI_PATH: "/swagger-ui.html"
