# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.22.0-standalone-strict/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-service
  namespace: finance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-service
  template:
    metadata:
      labels:
        app: news-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: diskType
                    operator: In
                    values:
                      - ssd
      containers:
        - name: news-service
          image: news-service
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: news-service-config
          resources:
            requests:
              cpu: "300m"
              memory: "1000Mi"
            limits:
              cpu: "500m"
              memory: "2000Mi"
