apiVersion: v1
kind: ConfigMap
metadata:
  name: openldap-config
data:
  LDAP_ORGANISATION: "Finance Portal"
  LDAP_DOMAIN: "finance.local"
  LDAP_READONLY_USER: "true"
  LDAP_READONLY_USER_USERNAME: "readonly"
