name: Build, Dockerize and Deploy

on:
  push:
    branches: [ "main", "master", "develop" ]

permissions:
  contents: read
  pull-requests: read
  packages: write  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect Changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            finance:
              - 'finance-service/**'
              - 'pom.xml'
            news:
              - 'news-service/**'
              - 'pom.xml'
            gateway:
              - 'api-gateway/**'
              - 'pom.xml'
            classification:
              - 'classification-api/**'
              - 'pom.xml'
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B clean package -DskipTests

      - name: Decode SSL Secrets into Files
        run: |
            mkdir -p keycloak/conf
            echo "${{ secrets.CRT_BASE64 }}" | base64 -d > keycloak/conf/keycloak.crt
            echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keycloak/conf/server.keystore  

      # ARM mimarisi (aarch64) için QEMU ve Buildx ayarları
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Finance Service
        if: steps.changes.outputs.finance == 'true'
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/finance-service
          docker buildx build --platform linux/arm64 -t $IMAGE:${{ github.sha }} -t $IMAGE:latest -f finance-service/Dockerfile --push .

      - name: Build & Push News Service
        if: steps.changes.outputs.news == 'true'
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/news-service
          docker buildx build --platform linux/arm64 -t $IMAGE:${{ github.sha }} -t $IMAGE:latest -f news-service/Dockerfile --push .

      - name: Build & Push API Gateway
        if: steps.changes.outputs.gateway == 'true'
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/api-gateway
          docker buildx build --platform linux/arm64 -t $IMAGE:${{ github.sha }} -t $IMAGE:latest -f api-gateway/Dockerfile --push .

      - name: Build & Push Ai News Analysis Service
        if: steps.changes.outputs.classification == 'true'
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/classification-api
          docker buildx build --platform linux/arm64 -t $IMAGE:${{ github.sha }} -t $IMAGE:latest -f classification-api/Dockerfile --push .
      

      - name: Copy SSL Files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_SSH_KEY }}
            source: "keycloak/conf/keycloak.crt,keycloak/conf/server.keystore"
            target: "~/myapp/"

      - name: Deploy to EC2
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/myapp
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -af
