name: Build and Dockerize

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect Changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            finance:
              - 'finance-service/**'
              - 'pom.xml'
            news:
              - 'news-service/**'
              - 'pom.xml'
            gateway:
              - 'api-gateway/**'
              - 'pom.xml'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B clean package -DskipTests

      - name: Build Finance Service Docker Image
        if: steps.changes.outputs.finance == 'true'
        run: docker build -t finance-service:latest -f finance-service/Dockerfile .

      - name: Build News Service Docker image
        if: steps.changes.outputs.news == 'true'
        run: docker build -t news-service:latest -f news-service/Dockerfile .

      - name: Build Api gateway Service Docker image
        if: steps.changes.outputs.gateway == 'true'
        run: docker build -t api-gateway:latest -f api-gateway/Dockerfile .